

"""
Stability analysis for SBM link reliability scores.

Runs Metropolis and the reliability calculation multiple times
using identical parameters but different random seeds.

Outputs:
- Reliability scores for each run
- Summary statistics across runs
- Link reliability stability across runs
- Top 20 predictions from all runs, side by side
- Frequency of each link appearing in the top 20

This script does not modify the main results generated by
results_reliability.py.
"""

from pathlib import Path
import sys

import networkx as nx
import numpy as np
import pandas as pd


# --------------------------------------------------
# Make the project root importable
# --------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from metropolis_sorin.metropolis import (
    initial_convergence,
    sample_different_groupings
)

from reliability_score.Link_reliability import (
    calculate_reliabilities,
    reliabilities_to_dataframe,
    reliability_statistics
)


# --------------------------------------------------
# Configuration
# --------------------------------------------------

NUMBER_OF_GROUPS = 16
INITIAL_STEPS = 3000
METROPOLIS_STEPS = 300000
NMI_THRESHOLD = 0.95
NUMBER_OF_CHANGES = 1

NUMBER_OF_RUNS = 5
RANDOM_SEED = 42
TOP_N = 20


def main():

    # --------------------------------------------------
    # 1. Load the observed network
    # --------------------------------------------------

    graph_path = (
        PROJECT_ROOT
        / "metropolis_sorin"
        / "foodweb_undirected.gml"
    )

    G = nx.read_gml(graph_path)

    nodes = list(G.nodes())
    A = nx.to_numpy_array(G, nodelist=nodes, dtype=int)

    taxon_names = {
        i: G.nodes[node].get("name", str(node))
        for i, node in enumerate(nodes)
    }

    # Save results separately from the main reliability results.
    results_dir = (
        Path(__file__).resolve().parent
        / "results"
        / "stability"
    )
    results_dir.mkdir(parents=True, exist_ok=True)

    all_run_statistics = []
    all_run_scores = []
    all_top20 = []
    all_top20_links = []

    # --------------------------------------------------
    # 2. Run repeated simulations
    # --------------------------------------------------

    for run in range(NUMBER_OF_RUNS):

        seed = RANDOM_SEED + run
        np.random.seed(seed)

        print(
            f"\nRun {run + 1}/{NUMBER_OF_RUNS} "
            f"(seed={seed}, K={NUMBER_OF_GROUPS})"
        )

        # Metropolis warm-up.
        initial_weight, initial_grouping = initial_convergence(
            A,
            NUMBER_OF_GROUPS,
            INITIAL_STEPS
        )

        # Sample partitions.
        accepted_groupings, accepted_groupings_weights = (
            sample_different_groupings(
                A,
                initial_weight,
                initial_grouping,
                NUMBER_OF_GROUPS,
                METROPOLIS_STEPS,
                NMI_THRESHOLD,
                number_of_changes=NUMBER_OF_CHANGES
            )
        )

        print(
            "Number of retained partitions:",
            len(accepted_groupings)
        )

        # Calculate reliability scores.
        reliabilities = calculate_reliabilities(
            A,
            accepted_groupings,
            accepted_groupings_weights,
            initial_weight,
            NUMBER_OF_GROUPS
        )

        reliability_df = reliabilities_to_dataframe(
            reliabilities
        )

        # Add taxon names.
        reliability_df["taxon_1"] = (
            reliability_df["node_1"].map(taxon_names)
        )
        reliability_df["taxon_2"] = (
            reliability_df["node_2"].map(taxon_names)
        )

        # --------------------------------------------------
        # Save reliability scores for this run
        # --------------------------------------------------

        reliability_df.to_csv(
            results_dir
            / f"reliability_scores_run_{run + 1}.csv",
            index=False
        )

        # --------------------------------------------------
        # Record summary statistics
        # --------------------------------------------------

        stats = reliability_statistics(
            reliability_df
        ).to_dict()

        stats["run"] = run + 1
        stats["seed"] = seed
        stats["retained_partitions"] = len(
            accepted_groupings
        )

        all_run_statistics.append(stats)

        # Keep scores for cross-run analysis.
        run_scores = reliability_df[
            ["node_1", "node_2", "reliability"]
        ].copy()

        run_scores["run"] = run + 1
        all_run_scores.append(run_scores)

        # --------------------------------------------------
        # Extract top 20 predictions
        # --------------------------------------------------

        top20 = (
            reliability_df
            .nlargest(TOP_N, "reliability")
            .copy()
        )

        # Keep node pairs for frequency comparison.
        top20_links = top20[
            ["node_1", "node_2"]
        ].copy()

        top20_links["run"] = run + 1
        all_top20_links.append(top20_links)

        # Create readable link names.
        top20["link"] = (
            top20["taxon_1"].astype(str)
            + " — "
            + top20["taxon_2"].astype(str)
        )

        # Prepare columns for side-by-side comparison.
        top20 = top20[
            ["link", "reliability"]
        ].reset_index(drop=True)

        top20.columns = [
            f"run_{run + 1}_link",
            f"run_{run + 1}_reliability"
        ]

        all_top20.append(top20)

        print("\nTop 5 predictions:")
        print(
            reliability_df[
                ["taxon_1", "taxon_2", "reliability"]
            ].head(5).to_string(index=False)
        )

    # --------------------------------------------------
    # 3. Compare summary statistics across runs
    # --------------------------------------------------

    stability_df = pd.DataFrame(
        all_run_statistics
    )

    stability_df.to_csv(
        results_dir / "baseline_stability.csv",
        index=False
    )

    # --------------------------------------------------
    # 4. Compare individual link scores across runs
    # --------------------------------------------------

    combined_scores = pd.concat(
        all_run_scores,
        ignore_index=True
    )

    link_stability = (
        combined_scores
        .groupby(["node_1", "node_2"])["reliability"]
        .agg(["mean", "std", "min", "max"])
        .reset_index()
    )

    link_stability["taxon_1"] = (
        link_stability["node_1"].map(taxon_names)
    )

    link_stability["taxon_2"] = (
        link_stability["node_2"].map(taxon_names)
    )

    link_stability.to_csv(
        results_dir / "baseline_link_stability.csv",
        index=False
    )

    # --------------------------------------------------
    # 5. Compare top 20 predictions side by side
    # --------------------------------------------------

    top20_comparison = pd.concat(
        all_top20,
        axis=1
    )

    top20_comparison.insert(
        0,
        "rank",
        range(1, TOP_N + 1)
    )

    top20_comparison.to_csv(
        results_dir / "top20_comparison.csv",
        index=False
    )

    # --------------------------------------------------
    # 6. Count how often links appear in the top 20
    # --------------------------------------------------

    combined_top20 = pd.concat(
        all_top20_links,
        ignore_index=True
    )

    top20_frequency = (
        combined_top20
        .groupby(["node_1", "node_2"])
        .agg(
            runs_in_top20=("run", "nunique")
        )
        .reset_index()
    )

    # Add taxon names.
    top20_frequency["taxon_1"] = (
        top20_frequency["node_1"].map(taxon_names)
    )

    top20_frequency["taxon_2"] = (
        top20_frequency["node_2"].map(taxon_names)
    )

    # Add mean and standard deviation across all runs.
    top20_frequency = top20_frequency.merge(
        link_stability[
            ["node_1", "node_2", "mean", "std"]
        ],
        on=["node_1", "node_2"],
        how="left"
    )

    top20_frequency = top20_frequency.sort_values(
        ["runs_in_top20", "mean"],
        ascending=[False, False]
    ).reset_index(drop=True)

    top20_frequency.to_csv(
        results_dir / "top20_frequency.csv",
        index=False
    )

    # --------------------------------------------------
    # 7. Print results
    # --------------------------------------------------

    print("\nStability summary:")

    print(
        stability_df[
            [
                "run",
                "seed",
                "retained_partitions",
                "mean",
                "median",
                "maximum"
            ]
        ].to_string(index=False)
    )

    print("\nTop 20 prediction frequency:")

    print(
        top20_frequency[
            [
                "taxon_1",
                "taxon_2",
                "runs_in_top20",
                "mean",
                "std"
            ]
        ].head(30).to_string(index=False)
    )

    print("\nStability results saved in:", results_dir)


if __name__ == "__main__":
    main()
